dynamic token;
dynamic userId;
dynamic name;
dynamic age;
dynamic phoneno;
dynamic sex;
dynamic weight;
dynamic ethnicity;
dynamic bodytype;
dynamic bodygoal;
dynamic email1;
dynamic image;
dynamic bloodPressure;
dynamic bloodSugar;
int isPremium = 0;
int isGoogleLogin = 0;
